spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTE_ID}
            client-secret: ${GOOGLE_CLIENTE_SECRETO}

# Seguridad relajada para desarrollo
app:
  security:
    dev-mode: true
